language: php
php:
    - 5.3
    - 5.4

before_script:
    - sudo apt-get install php-apc 
    - echo "extension=php-apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` 
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
 
script: 
   - cd ./tests/  
   - phpunit --bootstrap bootstrap.php .
