language: php
php:
    - 5.3
    - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - chmod -R 777 ./library/SimpleAnnotation/cache/
 
script: 
   - cd ./tests/  
   - phpunit --bootstrap bootstrap.php .
